name: 'Tests & Code coverage'

on:
    push:
      branches:
        - master

jobs:
  tests: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod download

      - name: Run test and converage
        run: go test ./... -v -coverprofile=coverage.out -covermode=atomic 

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3